version: '3.9'
secrets:
  test_db_1:
     file: test_db_1.txt

services:
  test_db:
    image: mysql
    deploy:
      replicas: 1
    secrets:
    - test_db_1
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/test_db_1
